### ISSUE TITLE
Error loading config file:/home/jenkins/.docker/config.json - EOF on fabric8 version 2.4.18 

### ISSUE THREAD

**Issue by J0hnson** [fabric8io/gofabric8#328] opened 2017-01-12 08:51 UTC
I installed fabric8 platform 2.4.18 on openshift:
openshift v1.3.1
kubernetes v1.3.0+52492b4
docker version 1.10.3

when i tried to create an application through fabric8,there is an error while running the Canary release.
The error message is :
***************************************************************
[?1034hsh-4.2# cd /home/jenkins/workspace/youtest

sh-4.2# sh -c echo $$ > '/home/jenkins/workspace/youtest@tmp/durable-a097e4f7/pi d'; jsc=durable-998f7519e69d4900f188d77b59d82fc8; JENKINS_SERVER_COOKIE=$jsc '/h ome/jenkins/workspace/youtest@tmp/durable-a097e4f7/script.sh' > '/home/jenkins/w orkspace/youtest@tmp/durable-a097e4f7/jenkins-log.txt' 2>&1; echo $? > '/home/je nkins/workspace/youtest@tmp/durable-a097e4f7/jenkins-result.txt'

+ docker build -t 172.30.191.130:80/fabric8/youtest:22b7db2 .

sh-4.2# exit

exit

**WARNING: Error loading config file:/home/jenkins/.docker/config.json - EOF

Cannot connect to the Docker daemon. Is the docker daemon running on this host?**

[Pipeline] }

[Pipeline] // container

[Pipeline] }

[Pipeline] // node

[Pipeline] }

[Pipeline] // node

[Pipeline] }

[Pipeline] // podTemplate

[Pipeline] }

[Pipeline] // node

[Pipeline] End of Pipeline

ERROR: script returned exit code 1

Finished: FAILURE

I logged in that pod named with kubernetes-xxxx, i found that the config file:/home/jenkins/.docker/config.json is empty.

It's appreciate for anyone to give some suggestions.

**Comment by J0hnson** [comment] 2017-01-12 08:58
![image](https://cloud.githubusercontent.com/assets/22162353/21883027/0abd6f74-d8e8-11e6-9080-2a0935335c8a.png)

**Comment by rawlingsj** [comment] 2017-01-12 09:28
That is just a warning and isn't the reason it fails, the problem seems to be that the docker socket mount and DOCKER_HOST env var are wrong perhaps.

These are defined in a shared pipeline library https://github.com/fabric8io/fabric8-pipeline-library/blob/master/vars/dockerTemplate.groovy#L15-L16

The docker socket from the host machine is mounted into the jenkins build pod so that we can perform docker builds. Do you know if the docker socket location on your host is different from our default of `/var/run/docker.sock`?  

If it is you can fork https://github.com/fabric8io/fabric8-pipeline-library update 

https://github.com/fabric8io/fabric8-pipeline-library/blob/master/vars/dockerTemplate.groovy#L15-L16
and 
https://github.com/fabric8io/fabric8-pipeline-library/blob/master/vars/mavenTemplate.groovy#L25-L26
to point to the correct location then change the @Library annotation at the top of your project Jenkinsfile to use your fork of the shared library.

**Comment by rawlingsj** [comment] 2017-01-12 11:37
FWIW I've recreated your issue on our openshift cluster and I'm looking into it.  BTW what OS and distribution are you running on your host machines?

**Comment by rawlingsj** [comment] 2017-01-12 12:58
@J0hnson forget what I was saying about the docker socket location, the issue is because the docker build pods aren't being run as privileged containers and therefore don't have permission to use the docker socket.  

I'm working on a fix.

**Comment by rawlingsj** [comment] 2017-01-12 13:55
@J0hnson if you change your project Jenkinsfile @Library URL to point to @master then you will pick up the fix I've just merged.  This means the docker commands now work.  

FWIW I'm going to add a feature to the pipelines that will switch to use openshift s2i rather than docker directly if running on openshift.

**Comment by rawlingsj** [comment] 2017-01-12 13:56
To pick up this fix the @LIbrary URL should look like..
```
#!/usr/bin/groovy
@Library('github.com/fabric8io/fabric8-pipeline-library@master')
```

**Closed by rawlingsj** 2017-01-12 13:55 UTC

**Comment by J0hnson** [comment] 2017-01-13 02:22
@rawlingsj 
Hi James,thanks for your reply first.
according to the check,my docker sock file is not different from your default location.
[root@repo run]# 
/usr/bin/docker-current daemon --exec-opt native.cgroupdriver=systemd --selinux-enabled --insecure-registry=registry.paastest.cn:443  --log-driver=json-file --log-opt max-size=50m --storage-driver devicemapper --storage-opt dm.fs=xfs --storage-opt dm.thinpooldev=/dev/mapper/docker--vg-docker--pool --storage-opt dm.use_deferred_removal=true
Jan 13 10:09:21 repo.paastest.cn docker-current[8250]: time="2017-01-13T10:09:21.021190699+08:00" level=info msg="Docker daemon" commit=3999ccb-unsupported execdriver=native-0.2 graphdriver=devicemapper version=1.10.3
Jan 13 10:09:21 repo.paastest.cn systemd[1]: Started Docker Application Container Engine.
Jan 13 10:09:21 repo.paastest.cn docker-current[8250]: time="2017-01-13T10:09:21.030198162+08:00" level=info msg="**API listen on /var/run/docker.sock"**

[root@repo run]# cat /var/run/docker.sock 
cat: /var/run/docker.sock: No such device or address
[root@repo run]# 

socket file cannot be "cat",right?:(

**Comment by J0hnson** [comment] 2017-01-13 08:21
@rawlingsj
Hi James
**1. what OS and distribution are you running on your host machines?**
I am using CentOS Linux release 7.3.1611 (Core) 

**"2. the docker build pods aren't being run as privileged containers and therefore don't have permission to use the docker socket."**
Is the docker build pods named with kubernetes-xxxx? I saw this pod  runs as privileged containers.
**3. I just followed your instruction to modify Jenkinsfile @Library URL to point to @master** 
But it failed with error:
**WARNING: Error loading config file:/home/jenkins/.docker/config.json - EOF**
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
![image](https://cloud.githubusercontent.com/assets/22162353/21922880/e6a3bcd2-d9ab-11e6-8a78-c9cb4424de39.png)

**Comment by J0hnson** [comment] 2017-01-13 09:11
If i want to use the registry outside of fabirc8 private regristy,is it modifying : 
  **stage 'Rollout Staging'
  kubernetesApply(file: rc, environment: envStage)**
to:
 **stage 'Rollout Staging'
  kubernetesApply(file: rc, environment: envStage, registry: 'myexternalregistry.io:443')**
?

**Comment by rawlingsj** [comment] 2017-01-13 09:34
@J0hnson that error with pushing to the registry is because you need the insecure flag added to each host machine DOCKER_OPTS.  Most kubernetes ansible installation scripts do this OOTB I maybe openshift ones dont as they prefer to use s2i.

If you have access to the host machines you can add this flag to your docker options and restart the docker service
```
--insecure-registry 10.0.0.0/8
```

FWIW I'm currently working on a version of pipelines that will automatically switch to use s2i if you're running on openshift.  This will avoid the need for pushing to that fabric8 docker registry if you don't have permission to add the insecure flag.  Hopefully I'll have these latest updates finished later today.

As for your other question, if you wanted to use a different registry then yeah you'd need to update 
```
kubernetesApply(file: rc, environment: envStage, registry: 'myexternalregistry.io:443')
```
but also change https://github.com/fabric8io/fabric8-pipeline-library/blob/master/vars/performCanaryRelease.groovy#L22 - you can fork that library and point to your version by updating the same `@Library` annotation in your jenkinsfile as you did before.  Having said that I'd expect you to hit the same issue without adding the insecure flag to your docker options.

**Comment by J0hnson** [comment] 2017-01-13 09:37
@rawlingsj 

Thanks,James.
Wait for your s2i. :+1:

**Comment by rawlingsj** [comment] 2017-01-14 18:56
fabric8 platform 2.4.19 has now been released which includes automatic pipeline switch to use [s2i binary source](https://docs.openshift.com/enterprise/3.2/dev_guide/builds.html#binary-source) if running on openshift.  

@J0hnson this avoids using the fabric8 docker registry and mounting the docker socket when installed on openshift so this should hopefully resolve all your issues.

**Comment by J0hnson** [comment] 2017-01-16 01:52
@rawlingsj 
Thanks very much James. The process works fine in 2.4.19 platform.
But i find that there is one issue about the image pulling and pushing.

I tried to create an php application called demo1, i saw the images was push to "Pushing image 172.30.0.3:5000/default/demo1:7631a33"  and the pipelines seems work fine.

![image](https://cloud.githubusercontent.com/assets/22162353/21968543/a5936fea-dbd0-11e6-81a0-46a22280fcd6.png).

but actually, the application was not deployed in staging and production env.
In staging and production env, there is problem with the generated image registry url in Deployment Config :
"  **image: 'null:null/fabric8/demo1:7631a33'"**.
So i think the auto generated Deployment Config file should be upgrade.

![image](https://cloud.githubusercontent.com/assets/22162353/21968593/22bd64d0-dbd1-11e6-8066-60d329f0fb31.png)

**Comment by rawlingsj** [comment] 2017-01-16 08:20
OK well it looks like the switch to use openshift s2i builds worked so we're close!

My guess is the env var I had on minishift to lookup the openshift docker registry is different to your cluster for some reason.  I was using `DOCKER_REGISTRY_SERVICE_HOST`.

Could you create a new test pipeline job via the jenkins UI and paste the below into the pipeline script text box of the job configuration?
```
node{
    sh 'env | grep 172.30.0.3'
}
```
We're looking for an environment variable name that we can use to in https://github.com/fabric8io/fabric8-pipeline-library/blob/master/vars/getKubernetesJson.groovy#L130 to find the openshift registry.  When the above script runs do you get any environment variables printed in the job console?

**Comment by J0hnson** [comment] 2017-01-16 08:47
![image](https://cloud.githubusercontent.com/assets/22162353/21975874/22ecb45e-dc0a-11e6-9e56-071e3d315df7.png)

![image](https://cloud.githubusercontent.com/assets/22162353/21975894/33df0ba4-dc0a-11e6-8a0c-163e6b4ebaec.png)
no information. Is the configuration right in jenkins UI?

**Comment by J0hnson** [comment] 2017-01-16 08:49
Following is the env in docker-registry pod:
![image](https://cloud.githubusercontent.com/assets/22162353/21976211/bbfe981e-dc0b-11e6-9f33-b3a9c7dba5ba.png)

**Comment by rawlingsj** [comment] 2017-01-16 08:53
> no information. Is the configuration right in jenkins UI?
No you need the ip address I used in the code snippet.  That's the kubernetes service ip address that it took from your s2i logs above.  Could you try the ip address rather than the dns name?

```
node{
    sh 'env | grep 172.30.0.3'
}
```

**Comment by J0hnson** [comment] 2017-01-16 09:04
[test] Running shell script
2 	+ env
3 	+ grep 172.30.0.3
4 	script returned exit code 1

i run env in node machine,there is no 172.30.0.3. Actually i configured --insecure-registry=registry.paastest.cn:443 in /etc/sysconfig/docker options

**Comment by rawlingsj** [comment] 2017-01-16 09:14
Ok so the issue here is that there's no environment variable in the jenkins build pod that helps us figure out what ip address to use for the openshift docker registry.  I'll need to do a bit of digging to see if that's a common thing for different openshift installs.  

Until then I think we can try another approach but I need to make a quick change to the shared pipeline library.  I'm travelling at the moment but will try and do it quickly now and report back of the steps to try shortly.

**Comment by J0hnson** [comment] 2017-01-16 09:22
Thanks,James. Wish you a nice trip.
I can modify the dc manually as a temporary solution .

Receiving source from STDIN as archive ...
14 	Step 1 : FROM fabric8/php:onbuild
15 	**Trying to pull repository registry.paastest.cn:443/fabric8/php ...** 
16 	Pulling repository registry.paastest.cn:443/fabric8/php
17 	Error: image fabric8/php not found
18 	Trying to pull repository docker.io/fabric8/php ... 
19 	Pulling from docker.io/fabric8/php
1569 	Pull complete
1570 	Digest: sha256:e571b2326a63e9af2328407f66ebf71a9cf0104f26ffb954936358f862252f14
1571 	Status: Downloaded newer image for docker.io/fabric8/php:onbuild
1572 	[91m# Executing 1 build trigger...
1573 	[0mStep 1 : COPY . /var/www/html/
1574 	 ---> 6cb113429245
1575 	Removing intermediate container 6731db694483
1576 	Step 2 : ENV "OPENSHIFT_BUILD_NAME" "demo1-s2i-1" "OPENSHIFT_BUILD_NAMESPACE" "default"
1577 	 ---> Running in 9fc206436e6e
1578 	 ---> 1bb316c260bd
1579 	Removing intermediate container 9fc206436e6e
1580 	Successfully built 1bb316c260bd
1581 	
1582 	**Pushing image 172.30.0.3:5000/default/demo1:7631a33 ...**

The image is pushed to "default ",is it should be "fabric8"

**Comment by J0hnson** [comment] 2017-01-17 01:38
another error is:
--> Scaling demo1-3 to 1
error: couldn't scale demo1-3 to 1: Scaling the resource failed with: User "system:serviceaccount:fabric8-staging:deployer" cannot update replicationcontrollers in project "fabric8-staging"; Current resource version 956075

**Comment by J0hnson** [comment] 2017-01-17 01:58
According to my latest test,i guess three things need to be upgraded:
1.No use registry: registry:"${env.FABRIC8_DOCKER_REGISTRY_SERVICE_HOST}:${env.FABRIC8_DOCKER_REGISTRY_SERVICE_PORT}" in deployProject.groovy, If this groovy file is used to generate "template:spec:containers:image" in the dc file.

2.Give deployer service account proper project privilege.
3.push images to fabric8 project not default project, not sure where to modify.

**Comment by rawlingsj** [comment] 2017-01-20 13:37
@J0hnson sorry for the delay but I've only just had a chance to take a look at this.  I've switched the shared library to use openshift imagestreams rather than the registry ip prefix so I hope this will solve the last problems.  If / when you get a chance could you try pointing your Jenkinsfile `@Library` annotation to my fork again and see if it all works for you?

So just as before, edit a php or nodejs project Jenkinsfile so the top looks like
```
#!/usr/bin/groovy
@Library('github.com/fabric8io/fabric8-pipeline-library@master')
```

and see if that now works.

**Comment by rawlingsj** [comment] 2017-01-20 13:49
I think I'll merge and kick off a new release after one last test anyhow, so you might want to wait for that to retry if you want.

**Comment by J0hnson** [comment] 2017-01-22 02:13
@rawlingsj 
Thanks,it works fine with pointing Jenkinsfile @Library to @master.
But there are many scripts approval.
Is there any way approval automatically or disable approval?
![image](https://cloud.githubusercontent.com/assets/22162353/22179333/5f7ce346-e08b-11e6-86d8-a145cba29f95.png)

**Comment by J0hnson** [comment] 2017-01-22 07:44
By the way,is there a good way to upgrade fabricc8 now? except using cleanup and deploy.

**Comment by rawlingsj** [comment] 2017-01-22 12:29
The script approvals are already done in the next release (available as of last night) so that will avoid that side affect of using my shared library branch. 

As for the upgrade, we don't have a better way yet however, we've got an auto updater planned hopefully a beta will be available as early as next week. This will provide a feature to either automatically update when a new version is available, roll back and hopefully even include a request for approval before updating too.

**Comment by J0hnson** [comment] 2017-01-23 05:22
@rawlingsj 
Thanks,james.
I post an issue based on the new version test.
https://github.com/fabric8io/gofabric8/issues/333
