### ISSUE TITLE
failed to "InitContainer" for "init" with RunInitContainerError: "init container \"init\" exited with 1" 

### ISSUE THREAD

**Issue by J0hnson** [fabric8io/gofabric8#315] opened 2016-12-15 05:56 UTC
I tried to install fabric8-platform-2.4.6 on openshift platform:
oc v1.3.1
kubernetes v1.3.0+52492b4
features: Basic-Auth GSSAPI Kerberos SPNEGO
openshift v1.3.1
kubernetes v1.3.0+52492b4

But failed to install gogs pod,the error messages:
Failed sync 	Error syncing pod, skipping: [failed to "InitContainer" for "init" with RunInitContainerError: "init container \"init\" exited with 1" , failed to "StartContainer" for "init" with CrashLoopBackOff: "Back-off 10s restarting failed container=init pod=gogs-5-8exat_fabric8(ad3620fb-c288-11e6-b27f-00248cfcb938)" ]

It seems that the annotation in gogs dc cannot run correctly:

  pod.alpha.kubernetes.io/init-containers: '[{"name":"init","image":"busybox","command":["chmod","777","/app/gogs/data"],"resources":{},"volumeMounts":[{"name":"gogs-data","mountPath":"/app/gogs/data"}],"terminationMessagePath":"/dev/termination-log","imagePullPolicy":"Always"}]'

It's appreciate for giving some advice.
Thanks,

**Comment by jstrachan** [comment] 2017-01-07 15:54
this is a duplicate of fabric8io/fabric8#6660 and its now fixed in fabric8 platform 2.4.15

**Closed by jstrachan** 2017-01-07 15:54 UTC

**Comment by J0hnson** [comment] 2017-01-10 07:42
@jstrachan
I just test again. I install fabric8 with command: "./gofabric8-linux-amd64 deploy -y --namespace=fabric8 --domain=paastest.cn --version=2.4.15"

But jenkins pod cannot be created successfully.
The error is the same as gogs

Error syncing pod, skipping: [failed to "InitContainer" for "init" with RunInitContainerError: "init container \"init\" exited with 1" , failed to "StartContainer" for "init" with CrashLoopBackOff: "Back-off 5m0s restarting failed container=init pod=jenkins-1-6gmtv_fabric8(e7b3edbd-d704-11e6-96d6-00221956ccce)" ]

Error syncing pod, skipping: failed to "InitContainer" for "init" with RunInitContainerError: "init container \"init\" exited with 1"

**Comment by J0hnson** [comment] 2017-01-10 07:53
I will create a new issue for Jenkins pod failure,since that gogs pod issue has been resolved in 2.4.15
